"""empty message

Revision ID: 865505e4d91c
Revises: 
Create Date: 2020-04-13 10:26:43.610496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865505e4d91c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athletes')
    # ### end Alembic commands ###
