"""empty message

Revision ID: fdbd88e5dbd4
Revises: 
Create Date: 2020-04-13 14:05:23.022758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbd88e5dbd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('avg_miles_per_week', sa.Integer(), nullable=True),
    sa.Column('avg_vertical_per_week', sa.Integer(), nullable=True),
    sa.Column('longest_run', sa.Integer(), nullable=True),
    sa.Column('longest_run_2_weeks', sa.Integer(), nullable=True),
    sa.Column('race_distance', sa.Integer(), nullable=True),
    sa.Column('race_veritcal', sa.Integer(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id', 'athlete_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('athletes')
    # ### end Alembic commands ###
